### ISSUE TITLE
okteto现在已经禁用websocket了

### ISSUE THREAD

**Issue by wang322588** [ygcaicn/Xray-heroku#13]
目前节点搭建都是ws，前两天已经被okteto封禁了，能不能直接部署个xray的xtls方案直连过去。

**Comment by wang322588** [comment]
并没有

**Comment by dinaau** [comment]
同样的问题
https://ray-xxx.cloud.okteto.net/  链接可以直接用浏览器打开

但是 v2客户端却无法连接成功 vless vmess都尝试过


 `2022/03/14 11:42:11 [Warning] core: Xray 1.5.3 started
2022/03/14 11:42:12 127.0.0.1:56980 accepted http://cachefly.cachefly.net/10mb.test [proxy10911]
2022/03/14 11:42:13 [Warning] [40958789] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://ray-xxx.cloud.okteto.net/s233): 404 Not Found > websocket: bad handshake
2022/03/14 11:42:13 [Warning] [40958789] proxy/http: failed to read response from cachefly.cachefly.net > io: read/write on closed pipe
`
