### ISSUE TITLE
连接报错

### ISSUE THREAD

**Issue by ginnycorn** [ygcaicn/Xray-heroku#2]
用了几个月一直很稳定，今天突然一直报错无法连接，试着用新的一键布署之后也还是不行…

failed to dial to (wss://打码.herokuapp.com/打码?ed=2048):  > write tcp 192.168.0.101:2864->3.224.183.135:443: i/o timeout github.com/v2fly/v2ray-core/v4/transport/internet/websocket: failed to dial WebSocket > github.com/v2fly/v2ray-core/v4/transport/internet/websocket: failed to dial to (wss://打码.herokuapp.com/打码?ed=2048):  > write tcp 192.168.0.101:11823->3.224.183.135:443: i/o timeout 

求助orz

**Comment by ygcaicn** [comment]
请问用的什么客户端，尝试换用XRay内核试试看

**Comment by ginnycorn** [comment]
> 请问用的什么客户端，尝试换用XRay内核试试看

PC用的V2rayN，设置里把core类型选为Xray_core以后报错如下

2021/06/19 13:01:58 [Warning] [3443877528] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://打码.herokuapp.com/打码):  > read tcp 192.168.0.101:3627->3.212.156.219:443: wsarecv: An existing connection was forcibly closed by the remote host.

手机端用v2rayNG，也报错context deadline exceeded

小白看起来整个就是远程连接失败o_O 是Heroku有什么问题吗，但是我在上面搭的ssh还可以用

**Comment by ginnycorn** [comment]
另外用新的一键部署之后生成的二维码扫描生成的配置端口是-1，手动改成443也还是连接不了…

**Comment by ygcaicn** [comment]
> > 请问用的什么客户端，尝试换用XRay内核试试看
> 
> PC用的V2rayN，设置里把core类型选为Xray_core以后报错如下
> 
> 2021/06/19 13:01:58 [Warning] [3443877528] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://打码.herokuapp.com/打码): > read tcp 192.168.0.101:3627->3.212.156.219:443: wsarecv: An existing connection was forcibly closed by the remote host.
> 
> 手机端用v2rayNG，也报错context deadline exceeded
> 
> 小白看起来整个就是远程连接失败o_O 是Heroku有什么问题吗，但是我在上面搭的ssh还可以用
> 
> 另外用新的一键部署之后生成的二维码扫描生成的配置端口是-1，手动改成443也还是连接不了…

新的一键部署之后生成的二维码扫描生成的配置端口是-1是脚本的bug，你的问题我暂时无法复现

**Comment by ginnycorn** [comment]
> > > 请问用的什么客户端，尝试换用XRay内核试试看
> > 
> > 
> > PC用的V2rayN，设置里把core类型选为Xray_core以后报错如下
> > 2021/06/19 13:01:58 [Warning] [3443877528] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://打码.herokuapp.com/打码): > read tcp 192.168.0.101:3627->3.212.156.219:443: wsarecv: An existing connection was forcibly closed by the remote host.
> > 手机端用v2rayNG，也报错context deadline exceeded
> > 小白看起来整个就是远程连接失败o_O 是Heroku有什么问题吗，但是我在上面搭的ssh还可以用
> > 另外用新的一键部署之后生成的二维码扫描生成的配置端口是-1，手动改成443也还是连接不了…
> 
> 新的一键部署之后生成的二维码扫描生成的配置端口是-1是脚本的bug(已修复)，无法连接的问题~我暂时无法复现~初步测试可能是被强了，加cf后可连接。
> 
> 将ProxySite默认值改为mirrors.kernel.org尝试一下。
> 
> http://xraytest2048.herokuapp.com/share233/index.html
> 这是我部署的24h后删除


配置成功
[VLESS] xraytest2048.herokuapp.com-Vless(xraytest2048***com:443)
启动服务(2021/6/20 0:16:22)...
Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 windows/386)
A unified platform for anti-censorship.
2021/06/20 00:16:23 [Info] infra/conf/serial: Reading config: G:\v2rayN-Core\config.json
2021/06/20 00:16:23 [Warning] core: Xray 1.4.0 started
2021/06/20 00:16:23 tcp:127.0.0.1:5667 accepted tcp:twitter.com:443 [socks >> proxy]
2021/06/20 00:16:23 tcp:127.0.0.1:13380 accepted tcp:twitter.com:443 [socks >> proxy]
2021/06/20 00:16:23 tcp:127.0.0.1:2292 accepted tcp:twitter.com:443 [socks >> proxy]
2021/06/20 00:16:24 127.0.0.1:2298 accepted tcp:127.0.0.1:0 [api -> api]
2021/06/20 00:16:24 tcp:127.0.0.1:4890 accepted tcp:twitter.com:443 [socks >> proxy]
2021/06/20 00:16:27 [Warning] [582096411] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xraytest2048.herokuapp.com/s233):  > read tcp 192.168.0.101:4898->3.86.21.156:443: wsarecv: An existing connection was forcibly closed by the remote host.
2021/06/20 00:16:27 [Warning] [2304741362] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xraytest2048.herokuapp.com/s233):  > read tcp 192.168.0.101:4897->3.86.21.156:443: wsarecv: An existing connection was forcibly closed by the remote host.
2021/06/20 00:16:27 [Warning] [3017443885] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xraytest2048.herokuapp.com/s233):  > read tcp 192.168.0.101:4899->3.86.21.156:443: wsarecv: An existing connection was forcibly closed by the remote host.
2021/06/20 00:16:28 [Warning] [429525798] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xraytest2048.herokuapp.com/s233):  > read tcp 192.168.0.101:4900->3.86.21.156:443: wsarecv: An existing connection was forcibly closed by the remote host.


之前搭的ssh虽然还能用但是看日志也是有报错的  是heroku的ip被盯上了嘛...
remote www.youtube.com:443 error: Error: connect ETIMEDOUT 34.240.104.255:80

**Comment by ygcaicn** [comment]
不使用科学环境，使用浏览器访问https://xraytest2048.herokuapp.com 如果打不开就是网络问题无疑了。

**Comment by ginnycorn** [comment]
> 不使用科学环境，使用浏览器访问https://xraytest2048.herokuapp.com 如果打不开就是网络问题无疑了。

打不开的…所以xray+heroku的方案就彻底被封锁了吗？不过ssh为什么还能用呢o_O

**Comment by ygcaicn** [comment]
> > 不使用科学环境，使用浏览器访问https://xraytest2048.herokuapp.com 如果打不开就是网络问题无疑了。
> 
> 打不开的…所以xray+heroku的方案就彻底被封锁了吗？不过ssh为什么还能用呢o_O

目前已恢复。
